### ISSUE TITLE
Error windows closes the program

### ISSUE THREAD

**Issue by TheLX5** [telinc1/faerie#3]
When an error window shows up, the program closes itself after closing the error window.

The most easy way to reproduce this is by trying to save an invalid CFG file:
- Open the program
- Ctrl+S

My Java version is 8, update 111 if this information helps.

**Comment by telinc1** [comment]
This is caused by the very rushed implementation of error messages. I wanted to get the pre-alpha version out before the end of the month (you might realize why), so I just cut some corners and used the default `ExceptionHandler`, which is definitely not how it should be done.

This issue is already known and will soon be fixed.
